[general]
import = [
  "~/.config/alacritty/tokyonight-night.toml"
  # "~/.config/alacritty/tokyonight-day.toml"
]

[window]


[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "Berkeley Mono", style = "Regular" }
size = 14
